### ISSUE TITLE
Suggestion to Simplify Endpoints for Follow and Unfollow Operations in User Service

### ISSUE THREAD

**Issue by rajkumardongre** [SohamRatnaparkhi/blogx-backend-go#1]
Hello @SohamRatnaparkhi, great job on your project! I have a suggestion regarding the User service API. Instead of using the `/follow?toFollowId=` endpoint, could we replace it with **`/follow?id=`**, and similarly, replace `/unfollow?toUnfollowId=` with **`/unfollow?id=`** I believe using `toFollowId` and `toUnfollowId` after `follow` and `unfollow` is redundant. Additionally, I think that using **`/follow?id=`** and **`/unfollow?id=`** would be more concise and meaningful.

**Comment by SohamRatnaparkhi** [comment]
Okay cool!

Will refractor the code soon.
Thank you!
